Repository honeycombio/libhoney-dotnet, pull requests merged in 2021-12, with the labels that each got.

#42 Add dependabot
  .github/dependabot.yml
Labels: version: no bump, type: maintenance, merge at will

#48 Fix authors, move examples and target netstandard2.0
  .circleci/config.yml
  .gitignore
  Directory.build.props
  Honeycomb.snk.gpg
  examples/Sample/Controllers/ValuesController.cs
  examples/Sample/Program.cs
  examples/Sample/Properties/launchSettings.json
  examples/Sample/Sample.csproj
  examples/Sample/Startup.cs
  examples/Sample/appsettings.json
  libhoney-dotnet.sln
  src/Honeycomb.AspNetCore/Honeycomb.AspNetCore.csproj
  src/Honeycomb.AspNetCore/HoneycombEventManager.cs
  src/Honeycomb.AspNetCore/Middleware/HoneycombMiddleware.cs
  src/Honeycomb/Honeycomb.csproj
Labels: version: bump minor, type: maintenance

#49 Prepare v1.2.0 release
  CHANGLOG.md
  RELEASING.md
  src/Honeycomb.AspNetCore/Honeycomb.AspNetCore.csproj
  src/Honeycomb/Honeycomb.csproj
Labels: version: no bump, type: maintenance
