Repository honeycombio/libhoney-dotnet, pull requests merged in 2022-10, with the labels that each got.

#75 Fix sample link in README.md
  README.md
Labels: type: documentation, version: no bump

#76 maint: add release file
  .github/release.yml
Labels: version: no bump, type: maintenance, merge at will, no-changelog

#77 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: version: no bump, type: maintenance, merge at will
