Repository honeycombio/libhoney-dotnet, pull requests merged in 2024-03, with the labels that each got.

#96 feat: support classic ingest keys
  src/Honeycomb/Honeycomb.csproj
  src/Honeycomb/Models/HoneycombApiSettings.cs
  test/Honeycomb.Tests/HoneycombApiSettingsTests.cs
Labels: type: enhancement, version: bump minor, merge at will

#97 rel: Prepare v1.4.0 release
  CHANGLOG.md
  src/Honeycomb.AspNetCore/Honeycomb.AspNetCore.csproj
  src/Honeycomb/Honeycomb.csproj
Labels: type: maintenance, no-changelog

#98 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: version: no bump, type: maintenance, no-changelog
